name: 02 - Workflow Events

on:
  push:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: |
          echo "Event name: ${{ github.event_name }}"

# Commit & push:
# ```bash
# git add .github/workflows/02-workflow-events.yaml
# git commit -m "Exercise 02: basic workflow with push trigger"
# git push
# ```
