name: Repository Dispatch from Repo A to Repo B

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build repo A"

      - name: Trigger repo B
        if: success()
        run: |
          curl -X POST https://api.github.com/repos/TheRealMamuth/work-jsystems-github-actions-examples-public/dispatches \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
          -d '{"event_type":"run-from-repo-a"}'
