---
- name: Deploy aplikacji w Dockerze
  hosts: all
  become: true

  vars:
    container_name: pogoda_api
    app_port: 8000

  tasks:

    # -------------------------
    # SYSTEM
    # -------------------------

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Instaluj zależności
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present

    # -------------------------
    # DOCKER (POPRAWNIE 2026)
    # -------------------------

    - name: Utwórz katalog keyrings
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Dodaj klucz Dockera (dearmor + poprawny fingerprint)
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
        gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Ustaw prawa do klucza
      file:
        path: /etc/apt/keyrings/docker.gpg
        mode: '0644'

    - name: Dodaj repozytorium Dockera (noble fix)
      apt_repository:
        repo: >
          deb [arch={{ ansible_facts['architecture'] }}
          signed-by=/etc/apt/keyrings/docker.gpg]
          https://download.docker.com/linux/ubuntu
          {{ ansible_facts['distribution_release'] }} stable
        state: present
        filename: docker

    - name: Update apt cache po repo
      apt:
        update_cache: yes

    # -------------------------
    # DOCKER INSTALL
    # -------------------------

    - name: Instaluj Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Uruchom Docker
      service:
        name: docker
        state: started
        enabled: true

    # -------------------------
    # DOCKER IMAGE
    # -------------------------

    - name: Pull obrazu
      community.docker.docker_image:
        name: "{{ docker_image }}"
        source: pull

    # -------------------------
    # CONTAINER
    # -------------------------

    - name: Usuń stary kontener
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent

    - name: Uruchom kontener
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}"
        state: started
        restart_policy: always
        recreate: true
        ports:
          - "8080:{{ app_port }}"
        env:
          OPENWEATHER_API_KEY: "{{ openweather_api_key }}"
